// Activity Actions
export const SET_ACTIVITY_RANGE = 'SET_ACTIVITY_RANGE';
export const GET_ACTIVITY_RANGE = 'GET_ACTIVITY_RANGE';
export const ACTIVITY_RANGE_MODIFIED = 'ACTIVITY_RANGE_MODIFIED';
export const FETCH_ACTIVITIES_BY_RANGE = 'FETCH_ACTIVITIES_BY_RANGE';
export const FETCH_ALL_ACTIVITIES_BY_RANGE = 'FETCH_ALL_ACTIVITIES_BY_RANGE';
export const ACTIVITIES_REQUESTED = 'ACTIVITIES_REQUESTED';
export const ACTIVITIES_RECEIVED = 'ACTIVITIES_RECEIVED';

// Activity Category Actions
export const FETCH_ACTIVITY_CATEGORIES = 'FETCH_ACTIVITY_CATEGORIES';
export const FETCH_ALL_ACTIVITY_CATEGORIES = 'FETCH_ALL_ACTIVITY_CATEGORIES';
export const CATEGORIES_REQUESTED = 'CATEGORIES_REQUESTED';
export const CATEGORIES_RECEIVED = 'CATEGORIES_RECEIVED';

// Event Request Actions
export const FETCH_PERMISSION = 'FETCH_PERMISSION';
export const PERMISSION_REQUESTED = 'PERMISSION_REQUESTED';
export const PERMISSION_RECEIVED = 'PERMISSION_RECEIVED'